Before after date filters
discourse/discourse-url-filters pull request #2
Opened 2021-12-15 22:59 UTC by oblakeerickson

Add `before_date` and `after_date` filters to filter topics by date in 'yyyy-mm-dd' format.

2021-12-15 23:33 UTC, oblakeerickson commented
https://github.com/discourse/discourse-url-filters/pull/1 should be merged in first

2021-12-16 03:12 UTC, CvX requested changes

2021-12-16 03:12 UTC, CvX commented on spec/plugin_spec.rb
> +      end
```suggestion
      fab!(:topic) { Fabricate(:topic, created_at: 10.days.ago) }
      fab!(:topic2) { Fabricate(:topic, created_at: 8.days.ago) }
      fab!(:topic3) { Fabricate(:topic, created_at: 6.days.ago) }
      fab!(:user) { Fabricate(:user) }
```

(references to those objects will have to be be changed, e.g. `@user` -> `user`)

2021-12-16 03:12 UTC, CvX commented on plugin.rb
> +          results = results.where('topics.created_at > ?', parsed_after_date) if parsed_after_date
```suggestion
          begin
            parsed_after_date = Date.parse(after_date)
            results = results.where('topics.created_at > ?', parsed_after_date)
          rescue Date::Error
          end
```

2021-12-16 03:12 UTC, CvX commented on plugin.rb
> +          results = results.where('topics.created_at < ?', parsed_before_date) if parsed_before_date
```suggestion
          begin
            parsed_before_date = Date.parse(before_date)
            results = results.where('topics.created_at < ?', parsed_before_date)
          rescue Date::Error
          end
```

2021-12-17 18:07 UTC, CvX approved these changes

2021-12-17 18:17 UTC, merged